### ISSUE TITLE
한국경제 작동 안 함

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#108]
http://www.hankyung.com/news/app/newsview.php?aid=201502200812i&nv=3

`ERROR: Execution of script 'jews' failed! Cannot read property '1' of null`
아마도 기자 목록을 파싱하는 데서 에러가 난 것으로 추정됩니다.

**Comment by yous** [comment]
http://www.hankyung.com/news/app/newsview.php?aid=201502200749i

![screenshot 2015-02-20 22 26 07](https://cloud.githubusercontent.com/assets/853977/6286865/839c510e-b94f-11e4-8599-d2a53974284d.png)

이 사이트에서 기자 목록을 파싱하는 것을 다시 생각해봐야 할 것 같습니다.

**Comment by disjukr** [comment]
본문에 기자 정보가 섞여있는 경우에는 그냥 파싱하지 않는다는 정책을 가져가도 될 것 같아요.
className 같은게 붙어있어서 확실하게 구분이 가능한 경우에만 뜯어내고..
