### ISSUE TITLE
한국경제: 파폭 36에서 Invalid Date

### ISSUE THREAD

**Issue by xnuk** [disjukr/jews#118]
http://www.hankyung.com/news/app/newsview.php?aid=2015032585437

**Comment by disjukr** [comment]
현재는 재현되지 않는군요. https://github.com/disjukr/jews/issues/124 와 동일한 이슈일 거라 추측됩니다.
비정형적인 날짜 정보를 파싱해주는 유틸 같은게 있으면 좋겠다는 생각이 드네요 ㄹㄹ

**Comment by xnuk** [comment]
![screenshot at 16-44-09](https://cloud.githubusercontent.com/assets/3071003/7111585/634f252c-e1fc-11e4-839f-fde2eeab25df.png)
파폭 37에서 재현됩니다.

**Comment by disjukr** [comment]
게에엑

**Comment by disjukr** [comment]
제가 멍청돋게 크롬에서 테스트 했군요(...)

**Comment by xnuk** [comment]
게에엑

**Comment by xnuk** [comment]
![입력 2015-03-25 14:39:00](https://cloud.githubusercontent.com/assets/3071003/7111690/8cddbede-e1fd-11e4-85d9-1693f6386291.png)

[L1863-1867](https://github.com/disjukr/jews/blob/d697df0f2fc1209488897ab0104ae72a88a2a1d4/jews.user.js#L1863-1867)에 구현되어 있는데 이게 한글이 들어가고 ISO 8601로 제대로 구현이 안 된지라 제대로 파싱하는 크롬이 신기한 겁니다(...
