### ISSUE TITLE
허핑턴포스트 일부 페이지에서 미동작

### ISSUE THREAD

**Issue by kall** [disjukr/jews#119]
http://www.huffingtonpost.kr/2015/03/27/story_n_6953236.html?utm_hp_ref=tw

허핑턴 전체가 그런건 아니고, 일부 기사에서 아래와 같은 익셉션 발생합니다.

>TypeError: Cannot read property 'textContent' of null
>    at parse.허핑턴포스트 (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:1986:65)
>    at parse (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:182:9)
>    at runJews (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:2309:5)
>    at Object.eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:2316:9)
>    at Object.eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:2322:4)
>    at d (eval at <anonymous> (unknown source), <anonymous>:27:64)
>    at eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:1:25)
>    at eval (native)
>    at m (eval at <anonymous> (unknown source), <anonymous>:53:418)
>    at Z (eval at <anonymous> (unknown source), <anonymous>:27:80)

**Comment by yous** [comment]
이전 구현의 경우 기자의 이름에 링크가 걸려있을 경우[1]에만 `.name.fn a[rel="author"]'`를 통해 가져올 수 있었습니다. 다만 기자 정보 부분이 전부 평문 문자열인 경우[2]도 있고, `'a[rel="author"] .name.fn'` 구조인 경우[3]도 있어 `.name.fn`을 바로 분석하도록 바꿨습니다.

1: <http://www.huffingtonpost.kr/2015/01/26/story_n_6544542.html?1422257219>
2: <http://www.huffingtonpost.kr/2015/03/27/story_n_6953236.html?utm_hp_ref=tw>
3: <http://www.huffingtonpost.kr/kyung-heo/story_b_6951988.html?utm_hp_ref=korea>
