### ISSUE TITLE
지디넷 이미지 크기

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#123]
http://www.zdnet.co.kr/column/column_view.asp?artice_id=20150412150752&type=xml

이미지가 너무 크게 나와서 레이아웃을 망치네요.
어떤 상황에서 원본 `width` 속성을 유지시켜주어야 할지 정책이 필요할 것 같습니다.

![2015-04-13 10 23 40](https://cloud.githubusercontent.com/assets/690661/7108620/303cd1aa-e1c7-11e4-8e64-251af3898793.png)

**Comment by disjukr** [comment]
원본 `width`를 유지시키는 것 말고도 휴리스틱을 적당히 버무려서 너무 얇은 텍스트 폭이 생기지 않도록 스타일을 조정시켜준다던가 할 수도 있을 것 같습니다.

**Comment by xnuk** [comment]
table에 `align=left`가 달려 있어서 저렇게 되네요. 이 경우는 이미지 사이즈는 그대로 놔두고 `align` 속성을 제거하는 게 나아 보입니다.

**Comment by xnuk** [comment]
그리고 jews가 원래 폭이 좁은데 단락 왼쪽이나 오른쪽에 (작게라도) 이미지를 둬서 폭을 더 좁게 만들면 가독성을 해치지 않을까 하는 게 제 개인적인 생각입니다.

**Comment by yous** [comment]
이미지 좌우에 글이 오지 않도록 처리할 수 있을까요?

**Comment by yous** [comment]
이제 이 이슈는 닫아도 될 것 같습니다.
