### ISSUE TITLE
$.fn.init.prototype.each가 jQuery와 동작이 다름

### ISSUE THREAD

**Issue by xnuk** [disjukr/jews#126]
![$(*)](https://cloud.githubusercontent.com/assets/3071003/7214248/3f0f5fc0-e5de-11e4-865a-d28f6896fa1e.png)
[L2038-2041](https://github.com/disjukr/jews/blob/ceddf11caec16098ab032bbdbc78fdd0f8ad45cc/jews.user.js#L2038-2041)에서 `fn.call(this, i, this[i]);`를 함으로써 인자로 받는 함수의 `this`가 여러 개의 element를 담은 `$` 객체(*위 코드를 기준으로* `$("*")`)로 되게 넘겼던데, 이는 [jQuery와 다르게 동작하는 부분](https://api.jquery.com/each/)입니다. 의도한 건가요?

**Comment by disjukr** [comment]
앗, 아뇨. jQuery와 동작이 다른 부분은 버그로 간주합니다.

**Comment by disjukr** [comment]
지금 `each`를 사용하고 있는 부분들도 재검토가 필요하겠네요.

**Comment by disjukr** [comment]
현상금 5천원 걸겠습니다. PR날릴 때 계좌번호 써주세요
