### ISSUE TITLE
세계일보에서 기사 내용이 두 번 나옴

### ISSUE THREAD

**Issue by khris** [disjukr/jews#149]
http://www.segye.com/content/html/2015/05/28/20150528000519.html

**Comment by disjukr** [comment]
음.. 크롬(43)과 파이어폭스DE(40)에서 테스트 해봤는데 재현되지 않네요.
재현 환경을 설명해주실 수 있나요?

**Comment by khris** [comment]
최신버전으로 업데이트 했더니 사라졌습니다 죄송합니다;;;

닫도록 하겠습니다.
