### ISSUE TITLE
블로터 찌꺼기 남음

### ISSUE THREAD

**Issue by item4** [disjukr/jews#153]
http://www.bloter.net/archives/230249

페이지 맨 하단부에 찌꺼기가 남아있습니다.

**Comment by disjukr** [comment]
제 환경(`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36`)에서는 재현이 되지 않는 듯 합니다.
문제가 발생한 환경에 대한 정보를 적어주실 수 있나요?

`‘체인지닷오아르지’에 등록된 페이스북 혐오 게시물 삭제 서명운동` 아래쪽에 다른 내용이 뜬다는 이야기죠?

![2015-06-15 5 10 05](https://cloud.githubusercontent.com/assets/690661/8155676/67cdc430-1381-11e5-87d4-7b4cc262f0a8.png)

**Comment by item4** [comment]
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0` 입니다.

사용중인 jews 버전은 0.10.0 이네요.

찌꺼기는 다음과 같습니다.

![Uploading 스크린샷 2015-06-15 오후 5.43.29.png…]()

**Comment by yous** [comment]
페이지 소스의 `<script type='text/javascript' src='http://www.bloter.net/wp-content/plugins/selection-sharer/js/selection-sharer.js?ver=0.1'></script>` 때문인 것으로 보입니다.
