### ISSUE TITLE
뉴스동아 찌꺼기 남음

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#156]
http://news.donga.com/List/3/0301/20130625/56091750/1

![2015-06-22 12 01 08](https://cloud.githubusercontent.com/assets/690661/8274941/881799d2-18d6-11e5-8c37-5410450c2a60.png)

![2015-06-22 12 01 13](https://cloud.githubusercontent.com/assets/690661/8274942/91327758-18d6-11e5-9167-e507a6e0adb3.png)

**Comment by yous** [comment]
제목이 누락되는 건 어느 환경인가요? `Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36`에선 제목이 보입니다.

**Comment by disjukr** [comment]
맥os 크롬이에요, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36` 입니다.

**Comment by disjukr** [comment]
헐 제 jews가 최신버전이 아니었네요 =_=;; 죄송합니다(...)

**Comment by disjukr** [comment]
앗, 잠시만 찌꺼기는 남네요(...)

**Comment by yous** [comment]
스크린샷을 한 번만 더 올려주시겠어요? #154 에서 좋아요 버튼은 제거했습니다.

**Comment by disjukr** [comment]
![2015-06-22 1 49 42](https://cloud.githubusercontent.com/assets/690661/8275668/8f5ffe00-18e5-11e5-8de3-6530e1580a42.png)
