### ISSUE TITLE
릴리즈 자동화

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#160]
요새 jews는 릴리즈가 잦을 수록 좋은 프로젝트일 것이라는 생각이 듭니다.
버저닝 방식을 semver를 사용하는 대신 `yyyy-mm-dd`를 포맷으로 해서

1. CI 등을 통해서 빌드를 자동화하고
2. master 브랜치에 변경사항이 존재하고 테스트가 안정적으로 통과되면
3. 빌드 봇이 자동으로 릴리즈까지 처리하는 방식이 좋지 않을까 싶습니다.

이를 구현하기 위해서는 https://github.com/disjukr/jews/issues/19 이 이슈가 선결 되어야 할 것 같습니다.

이에 대해 다른 분의 의견도 듣고 싶습니다.

**Comment by yous** [comment]
전 좋습니다. 테스트가 문제겠군요.

**Comment by minhoryang** [comment]
+1 사용자에게 업데이트 푸시만 할 수 있다면 최고 아닌가요?

**Comment by xnuk** [comment]
설사 테스트를 넣는다고 해도 모든 뉴스 사이트가 전부 테스트를 통과하는 경우는 별로 없을 거 같아서() 릴리즈를 없애고 그냥 사용자에게 최신 버전을 제공하는 게 낫지 않을까 싶습니다.

**Comment by disjukr** [comment]
https://circleci.com/docs/nightly-builds
circle ci가 nightly build를 지원하는 것 같습니다.

작성된 테스트가 딱히 없더라도, 적어도 빌드가 성공하는지 여부는 보고 자동으로 릴리즈 하는 정도도 훌륭할 것이라고 생각합니다.
