### ISSUE TITLE
뉴스원 하단에 광고가 표시됩니다.

### ISSUE THREAD

**Issue by youngminz** [disjukr/jews#166]
http://news1.kr/articles/?1648522

**Comment by yous** [comment]
이 기사는 태그가 잘못 작성되어 있어서 파싱하기 어려운 구조가 되어버렸네요. 이게 일반적인 기사입니다. http://news1.kr/articles/?2337721

**Comment by youngminz** [comment]
확인해보니 정말 아티클과 광고가 같은 태그에 묶여 있네요.

**Comment by yous** [comment]
광고를 그나마 줄일 수 있는 방법을 찾아보는 게 좋겠네요.

**Comment by xnuk** [comment]
보니까 `<table>` 태그가 닫히지 않아서 일어난 문제네요.

**Comment by yous** [comment]
@youngminz 한 번 확인해주세요. https://github.com/disjukr/jews/commit/a2f5158593f6c32723086520b7e04a0842602ca8

**Comment by youngminz** [comment]
광고 없이 잘 작동하네요. 감사합니다! :)
