### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by yous** [disjukr/jews#19]
I think we need sample html pages for each site and expected result html pages to test basic functionality. Can we mock the root DOM and run `jews.user.js` against to it?

**Comment by minhoryang** [comment]
+1

**Comment by disjukr** [comment]
현상금 만원 걸겠습니다. PR날릴 때 계좌번호 써주세요

**Comment by disjukr** [comment]
테스팅이 중요하다고 생각돼서.. https://github.com/disjukr/jews/pull/140 에서 붕 뜨게 된 현상금은 이쪽에 붙이겠습니다.

**Comment by disjukr** [comment]
https://github.com/disjukr/jews/pull/133 여기서 붕 뜨게 된 것도=3

**Comment by xnuk** [comment]
2만 원이군요

**Comment by item4** [comment]
[casperjs](https://github.com/n1k0/casperjs) 를 써서 구현하기로..

누가 할지는... ?

**Comment by disjukr** [comment]
@item4 감사합니다

**Comment by disjukr** [comment]
2만원 결국 제가 가져갔다고 합니다(?)
