### ISSUE TITLE
IT World 안 됨

### ISSUE THREAD

**Issue by item4** [disjukr/jews#193]
http://www.itworld.co.kr/news/96332

**Comment by disjukr** [comment]
`v2015-10-16` 기준 크롬에서는 잘 되네요 제 `userAgent`는 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36`입니다.

혹시 문제가 발생하는 환경이 어떻게 되나요?

**Comment by item4** [comment]
jews를 다시 까니 잘 됩니다. 닫겠습니다. (...)
