### ISSUE TITLE
ytn 광고

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#197]
http://www.ytn.co.kr/_ln/0104_201511130431412551_005

![2015-11-13 12 10 37](https://cloud.githubusercontent.com/assets/690661/11137922/b1a793ca-89ff-11e5-966d-7431220b2285.png)

**Comment by yous** [comment]
'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36'에선 안 보이는데, 재현 조건이 뭔가요?

**Comment by disjukr** [comment]
전 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36`이긴 한데, 문제는 환경과는 무관해보이고.. 지금은 저 광고가 안보이네요ㅠ

`div[id^=float]` 패턴으로 잡히는 광고였습니다. 아래쪽 작은 div는 id가 float2에요

**Comment by yous** [comment]
일단은 어떻게 가리는 게 좋을지 모르겠으니 놔두겠습니다. 닫았다가 다시 재현되면 여는 게 나을 수도 있겠네요.

**Comment by disjukr** [comment]
음 그럼 일단 닫는 걸로..

**Comment by disjukr** [comment]
재발
http://www.ytn.co.kr/_ln/0104_201511191204293407

![2015-11-19 7 33 45](https://cloud.githubusercontent.com/assets/690661/11268499/7e7fb01e-8ef4-11e5-8ef2-1260e5532668.png)
