### ISSUE TITLE
연합뉴스 작동 안함

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#199]
http://www.yonhapnews.co.kr/politics/2015/11/15/0501000000AKR20151115051951001.HTML
`jews don't support this site`

문제가 되는 코드:
https://github.com/disjukr/jews/blob/master/src%2Fsites.js#L64 또는
https://github.com/disjukr/jews/blob/master/src%2Fjews.user.js#L42

**Comment by disjukr** [comment]
`RegExp.escape(pattern).replace(/\\\*/g, '.+?')` 이 부분을

1. `RegExp.escape(pattern).replace(/\\\*/g, '.*?')`
2. `RegExp.escape(pattern).replace(/\\\*/g, '.*')`

둘 중 어느 방식으로 바꾸는게 좋을까요

**Comment by yous** [comment]
전 `.*`로 바꿔도 될 것 같습니다.
