### ISSUE TITLE
한국경제TV 작동 안함

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#207]
http://sports.wowtv.co.kr/news/view.asp?newsid=WS00000025908

sites 목록에 url 패턴 추가해야합니다.

**Comment by teslamint** [comment]
링크가 깨졌네요

**Comment by disjukr** [comment]
@teslamint 잘 모르겠지만 아마 정기점검시간 중이라 그런 것 같습니다: http://wowtv.co.kr/
![2016-01-30 11 41 58](https://cloud.githubusercontent.com/assets/690661/12696320/1d6155fe-c7ab-11e5-87b5-3c568f3d00cb.png)

**Comment by teslamint** [comment]
@disjukr 404 뜨네요. 개편하면서 주소가 바뀐 것으로 보입니다. http://www.wowtv.co.kr/newscenter/news/view.asp?artid=A201511210001

**Comment by disjukr** [comment]
@teslamint 링크하신 주소로 jews가 잘 도네요. 이 이슈는 닫도록 하겠습니다.
