### ISSUE TITLE
머니투데이 광고

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#215]
http://www.mt.co.kr/view/mtview.php?type=1&no=2015103016163507564&outlink=1

![2015-11-30 12 09 38](https://cloud.githubusercontent.com/assets/690661/11462735/6034a7a8-975b-11e5-8641-fb746b66cae1.png)

**Comment by disjukr** [comment]
광고는 테스트 어떻게 하는게 좋으려나...

**Comment by teslamint** [comment]
fixed with https://github.com/disjukr/jews/commit/d37bfcccefd423cf2ebeb5d06587d3fc4c23ecdc
