### ISSUE TITLE
스포츠서울 작동 안함

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#216]
http://www.sportsseoul.com/news/read/326593

`sites.js`: url 패턴 추가해야함

**Comment by yous** [comment]
사이트가 바뀐 것 같으니 예전 URL 패턴은 일단 지워두겠습니다.

**Comment by disjukr** [comment]
@yous 가능하면 테스트 케이스에도 이슈번호와 함께 추가해주시면 감사..
https://github.com/disjukr/jews/blob/master/src%2Ftest%2Fsuite%2Fsites.js#L12

**Comment by yous** [comment]
앗, 감사합니다. 추가했습니다. https://github.com/disjukr/jews/commit/c9ff078140eace55f2ee3a9d82633bca88a8d419

**Comment by disjukr** [comment]
:+1:
