### ISSUE TITLE
sbs 잘못된 마지막 수정일

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#218]
http://news.sbs.co.kr/news/endPage.do?news_id=N1003295957#sns

![2015-12-03 1 57 05](https://cloud.githubusercontent.com/assets/690661/11552260/e93622f4-99c5-11e5-8072-4863c7bdbfb6.png)

테스트 케이스 추가 필요: https://github.com/disjukr/jews/blob/master/src%2Ftest%2Fsuite%2Fbasic.js#L50

**Comment by yous** [comment]
#228 수정을 하면서 같이 해결되었습니다.
