### ISSUE TITLE
테스트 통과시키기

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#226]
으.. 머지된 PR을 릴리즈시키기 위해서 저번주 중으로 테스트 통과시키기로 했었는데
바빠서 깜빡 잊고 있었습니다.
1/6까지 제출인 대회가 있어서 그 주의 주말인 1/9 ~ 1/10 중에 작업하겠습니다.

**Comment by yous** [comment]
:+1:

**Comment by disjukr** [comment]
:shipit:
