### ISSUE TITLE
헤럴드경제 광고

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#234]
광고인지 구분할 수 있는 근거가 적어서 제거하는 게 어려울지도 모르겠습니다.

http://news.heraldcorp.com/view.php?ud=20151228000616&md=20151231154112_BL

![2016-01-30 3 44 05](https://cloud.githubusercontent.com/assets/690661/12694194/6f3fdaa0-c768-11e5-8cdd-b32213a998bc.png)

**Comment by item4** [comment]
URL에 패턴이 있지 않을까요

**Comment by item4** [comment]
`http://res.heraldm.com/content/2016/01/29/20160129090101_ADfd_srcfile_106_243_243_60_8101.jpg`

src 중간에 `_ADfd_`란 글자가 들어가면 광고라고 본다던가..

**Comment by teslamint** [comment]
`$('center > span img')`로 걸러낼 수 있을 거 같네요.

**Comment by disjukr** [comment]
http://biz.heraldcorp.com/view.php?ud=20160129000014
이 링크는 `center`를 사용하지 않고 `table`을 사용하네요.
`$('span > a:only-child > img:only-child[src*=_ADfd_]').closest('span')` 이런 느낌으로 걸러지기는 할 것 같습니다.
