### ISSUE TITLE
source map 데이터 분리

### ISSUE THREAD

**Issue by teslamint** [disjukr/jews#254]
릴리즈되는 js 파일에 보면 소스코드맵 데이터가 마지막 줄에 들어가 있는데 이게 수십만 바이트짜리 base64 인코딩된 텍스트가 한 줄로 들어있다 보니 Tampermonkey 등에서 수정한 코드를 복붙하거나 스크롤하면 브라우저가 한참 동안 hang에 걸리는 문제가 있네요.
그래서 별도로 map 파일을 만들어 github 등에 호스팅하는 게 나을 거 같습니다.

**Comment by disjukr** [comment]
빌드스크립트를 보니 프로덕션 빌드에 uglify도 빼먹었네요.. 이걸 왜 못봤지 ㅋㅋㅋㅋ

**Comment by disjukr** [comment]
프로덕션 빌드를 태우면 소스맵 파일을 분리하고 url을 깃헙으로 넣어놨어요.
`npm run build`시에 자바스크립트 파일 안에 주석으로 소스맵을 때려박은건 디버깅을 해야해서...
탬퍼몽키에 매번 복붙하는 대신 특정 로컬파일을 바라보게 하는 기능이 있으면 좋을 것 같네요 ㄹㄹ
아무튼 탬퍼몽키에 빠르게 복붙해서 돌려보려면 `npm run production`으로 빌드해서 복붙하면 될 거에요.

**Comment by disjukr** [comment]
는 계속 트래비스 테스트 타임아웃이 뜨네요... 왜지...

**Comment by item4** [comment]
지금 보니 node 버전이 4인데, 그거랑 같이 경고가 뜹니다.

```
Updating nvm to v0.31.0

2.02s$ nvm install 4

Downloading https://nodejs.org/dist/v4.4.5/node-v4.4.5-linux-x64.tar.xz...

######################################################################## 100.0%

Now using node v4.4.5 (npm v2.15.5)

Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
```
