### ISSUE TITLE
fuse-box로 넘어가기

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#260]
#243 이랑 같이 되면 좋을 듯

**Comment by item4** [comment]
제가 개인 프로젝트에서 webpack2를 올렸더니 uglifyjs랑 말썽을 빚었습니다. harmony지원이 안 되서 그런거 같던데 좀 나중에 하는게 어떨까요

**Comment by disjukr** [comment]
그렇군영. 나중에 하져 머

**Comment by disjukr** [comment]
그나저나 uglifyjs 말고 바벨 미니파이던가 그거 써볼까 싶긴 해요

**Comment by disjukr** [comment]
https://github.com/fuse-box/fuse-box 헉 이거 조아보인당
