### ISSUE TITLE
프로젝트 이름 바꾸기

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#262]
jews는 유대인을 뜻하는 말이므로 프로젝트 이름으로 부적절하다는 지적을 여럿 들어온 바 있어 늦었지만 지금이라도 프로젝트 이름을 바꾸려고 합니다.
짧은 이름으로 하되 가능하면 동명의 프로젝트가 없으면 좋겠습니다.

개인적으로 고려중인 프로젝트명 후보는 다음과 같습니다:

- `articlean`
- `news-only`
- `just-news`

새로운 이름 제안 받습니다.

**Comment by minhoryang** [comment]
+1 `just-news`

**Comment by yous** [comment]
원래 프로젝트 이름이 `just-news`에서 온 만큼 이게 가장 무난하네요.

**Comment by teslamint** [comment]
+1 just-news

**Comment by KimKyung-man** [comment]
+1 `just-news`
