### ISSUE TITLE
모바일 뉴스페이지, 포털사이트 뉴스페이지를 지원 사이트 목록에 추가할 예정

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#54]
* [x] 포털사이트 뉴스페이지 목록 추가
* [ ] 모바일 뉴스페이지 목록 추가

**Comment by item4** [comment]
모바일 뉴스페이지를 지원하는건 좋은데, 모바일에서도 jews를 쓸 수 있을까요?

**Comment by disjukr** [comment]
@item4 음..

1. 모바일 파이어폭스에서 유저스크립트를 쓸 수 있다고 들었어요.
2. 모바일 뉴스페이지 지원은 pc에서 모바일 링크로 들어갔을 때 작동하게 만들고 싶어서요.
3. 근데 그냥 모바일 링크로 들어가면 pc 링크로 리디렉션 시켜주는 유저스크립트를 따로 만들까 해요.

**Comment by disjukr** [comment]
### 포털예시
- 네이버: http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&oid=421&aid=0001723136&sid1=001&lfrom=twitter
- 다음: http://media.daum.net/society/education/newsview?newsid=20151109113006727
- 네이트: http://news.nate.com/view/20151109n02843

음.. 추가할만한 포털사이트가 더 있을까요?

**Comment by disjukr** [comment]
모바일 뉴스페이지는 추가하지 않기로 하고 이슈를 닫겠습니다.
