### ISSUE TITLE
자체구현 jQuery 들어내기

### ISSUE THREAD

**Issue by disjukr** [disjukr/jews#75]
`@require` 메타데이터를 이용하는 쪽이 좋을 것 같습니다:
 * tampermonkey 지원: http://tampermonkey.net/documentation.php#_require
 * greasemonkey 지원: http://wiki.greasespot.net/Third-Party_Libraries
 * ninjakit 지원: http://os0x.hatenablog.com/entry/20100612/1276330696
 * trixie도 지원하는지는 잘 모르겠네요. @SaschaNaz help

```javascript
// @require    http://code.jquery.com/jquery-2.1.1.min.js
```

**Comment by yous** [comment]
Closed via https://github.com/disjukr/jews/commit/ae3a291474c8b34c4d934d078b3bd3975508887c.
